### ISSUE TITLE
PYPI package seems to have wrong preprocess.py dependency

### ISSUE THREAD

**Issue by utsekaj42** [hplgit/doconce#171]
I discovered today that installing with pip in Python 3 results in this error which is not present in the "doconce/preprocess.git". Perhaps the dependencies just need to be updated on PYPI. 

```
(testdoinst) [jsturdy@dhcp-088105 doconce]pip install doconce
Collecting doconce
  Using cached https://files.pythonhosted.org/packages/41/b8/0072e50ef282b969f4694ea6b22aeec81aeb15dff9104d5cb7793a573fdb/DocOnce-1.4.3.tar.gz
Collecting pygments (from doconce)
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 8.2MB/s 
Collecting preprocess (from doconce)
  Downloading https://files.pythonhosted.org/packages/05/f9/559841df6c91428a2024ce120d92192844178e4b2ceec1da84ce18205380/preprocess-1.1.0.zip (59kB)
    100% |████████████████████████████████| 61kB 16.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vzku6ntm/preprocess/setup.py", line 28, in <module>
        import preprocess
      File "/tmp/pip-install-vzku6ntm/preprocess/lib/preprocess.py", line 264
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax
```

**Comment by KGHustad** [comment]
The PyPI package hasn't been updated in a while. I've uploaded 1.4.10 now. Unfortunately, I do not have the permissions to update the preprocess package on PyPI, which is really outdated. Consequently I changed `setup.py` so that DocOnce will not pull in (an outdated Python 2 only version of) preprocess automatically.
