### ISSUE TITLE
anaconda doconce install error 

### ISSUE THREAD

**Issue by nagordon** [hplgit/doconce#26]
I am not sure if this is a conda error or not, just just wanted to let you know

Linux Mint 17.1
installed Anaconda
```bash
bash Anaconda-2.2.0-Linux-x86_64.sh
```
I closed the terminal and opened a new one.
```bash
neal@cinnamon ~ $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.12.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : /home/neal/anaconda  (writable)
  default environment : /home/neal/anaconda
     envs directories : /home/neal/anaconda/envs
        package cache : /home/neal/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
```

when I try to install 
```bash
conda install --channel johannr doconce
```

I get the error
```bash
doconce-1.0.3- 100% |################################| Time: 0:00:03   1.77 MB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the########     |  90%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/neal/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    try:
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    log.debug("Can't write the history file")
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    if to_link:
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
    return dist, pkgs_dir, int(linktype)
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
    if pkgs_dir is None:
  File "/home/neal/anaconda/lib/python2.7/site-packages/conda/install.py", line 523, in link
    
  File "/home/neal/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/neal/anaconda/lib/python2.7/site-packages/snowballstemmer-1.2.0-py2.7.egg-info'
```

I also tried doing the complete install as root and I get the same error. I however, used the install [script](https://raw.githubusercontent.com/hplgit/doconce/master/doc/src/manual/install_doconce.sh)
with success.

I am really excited to see this project grow. Awesome work!

**Comment by johannesring** [comment]
Thanks @nagordon for the report. This should be fixed now. Please let us know if it works for you.

**Comment by nagordon** [comment]
I ran the conda package and it appeared to work. Thanks
