### ISSUE TITLE
Unicode chars in title does not compile properly to html

### ISSUE THREAD

**Issue by lourenko** [hplgit/doconce#35]
Hi,

I try to make a presentation with the line:
TITLE: Sustentação
and got the following error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/doconce", line 1177, in <module>
    main()
  File "/usr/local/bin/doconce", line 1167, in main
    eval(command + '()')
  File "<string>", line 1, in <module>
  File "/usr/local/bin/doconce", line 92, in format
    doconce.doconce.format_driver()
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 4499, in format_driver
    out_filename = file2file(filename_preprocessed, format, basename)
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 3478, in file2file
    filestr = doconce2format(filestr, format)
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 3905, in doconce2format
    filestr = INTRO[format] + filestr
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)
```

To overcome the situation I just added these two lines in make.sh:

```make
doconce replace '<h1>Sustentacao</h1>' '<h1>Sustentação</h1>' $name.html
doconce replace '<title>Sustentacao</title>' '<title>Sustentação</title>' $name.html
```

Interestingly was that it accepts:

AUTHOR: Sustentação

but not:

TITLE: Sustentação

I used the beige theme, where just TITLE is made a little glossy.

Thanks in advance,

**Comment by hplgit** [comment]
Hi,

I tried the following test document:

```
TITLE: Sustentação
AUTHOR: Sustentação
DATE: today

We write some unicode: Sustentação.
```
and compiled it to plain html, Bootstrap html, and reveal.js beige slides html:

```
doconce format html test3 --encoding=utf-8
doconce format html test3 --encoding=utf-8 --html_style=bootstrap
doconce slides_html test3 reveal --html_slide_theme=beige
```

The title comes out right in all cases.

Can you provide your test example and the commands you are running?

**Comment by lourenko** [comment]
Thank you for the fast answer.  A make a new test, called test.do.txt:

```markdown
TITLE: Sustentação
AUTHOR: Marcos Lourenço
DATE: Sexta, 12 de junho de 2015

!split
===== Test unicode Ação =====

!bslidecell 00 0.6
 * Only a simple
 * Test!
!eslidecell
```

And compile the code with a make.sh:

```console
name=test
doconce format html $name
doconce format html $name --encoding=utf-8
doconce format html $name --encoding=utf-8 --html_style=bootstrap
doconce slides_html $name reveal --html_slide_theme=beige
```

And still returning an error at the output:

```python
translating doconce text in test.do.txt to html
Traceback (most recent call last):
  File "/usr/local/bin/doconce", line 1177, in <module>
    main()
  File "/usr/local/bin/doconce", line 1167, in main
    eval(command + '()')
  File "<string>", line 1, in <module>
  File "/usr/local/bin/doconce", line 92, in format
    doconce.doconce.format_driver()
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 4499, in format_driver
    out_filename = file2file(filename_preprocessed, format, basename)
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 3478, in file2file
    filestr = doconce2format(filestr, format)
  File "/usr/local/lib/python2.7/dist-packages/doconce/doconce.py", line 3905, in doconce2format
    filestr = INTRO[format] + filestr
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)
translating doconce text in test.do.txt to html
open file with encoding utf-8
output in test.html
translating doconce text in test.do.txt to html
open file with encoding utf-8
output in test.html
slides written to test.html
```

I'm using kubuntu 15.

**Comment by lourenko** [comment]
When I remove the first line of make.sh, it compiles properly. In this case, the make.sh is:
```makefile
name=test
doconce format html $name --encoding=utf-8
doconce format html $name --encoding=utf-8 --html_style=bootstrap
doconce slides_html $name reveal --html_slide_theme=beige
```
It is all good now. Thanks for the nice package and for the help!

**Comment by hplgit** [comment]
If you update to the most recent doconce version, you will get a sensible error message about missing encoding in your test case, rather than the UnicodeDecodeError from Python.
